### ISSUE TITLE
[Bug]: xterm disappear after run

### ISSUE THREAD

**Issue by vickyorlo** [bottlesdevs/Bottles#1330]
### Describe the bug

When clicking the "Command line" option under utilities, an xterm window shows up for a single frame and then disappears. A command line thus does not appear. It is difficult to say what the text says during this single frame, but I made a recording - the message displayed is the same as when running `wine` without any parameters, ie:
```
Usage: wine PROGRAM [ARGUMENTS...]   Run the specified program
       wine --help                   Display this help and exit
       wine --version                Output version information and exit
```

### To Reproduce

1. Create a new bottle
2. Click "Command line" under the Utilities tab

### Package

AUR ("bottles" package)

### Distribution

Arch Linux

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.1-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Fixed, will be distributed with 2022.4.28

**Comment by vickyorlo** [comment]
I built from git - this isn't quite fixed. Right now, xterm does open and stay up, but no input is allowed. It simply hangs on the wine help message. I think you want to run `wine cmd` rather than just `wine`. Also, stealth feature request - Lutris has an option to simply open your regular shell with all of the environment variables and such set - I would like to have this as another option. I imagine doing the same thing as here but instead of calling `wine cmd` you would call `$SHELL` would suffice.
