### ISSUE TITLE
[BUG] Incomplete translations on Flatpak package

### ISSUE THREAD

**Issue by LeandroStanger** [bottlesdevs/Bottles#174]
**Describe the bug**
Some parts of the Bottles are translated and others are not translated

**Installation**
Flatpak (Flathub beta)

**Expected behavior**

**Screenshots**
![Captura de tela de 2021-03-09 09-05-58](https://user-images.githubusercontent.com/26097419/110468632-4f230e00-80b7-11eb-865f-8154ad6097df.png)
![Captura de tela de 2021-03-09 09-05-44](https://user-images.githubusercontent.com/26097419/110468650-521dfe80-80b7-11eb-9a0c-3340e06dd2a0.png)
![Captura de tela de 2021-03-09 09-06-02](https://user-images.githubusercontent.com/26097419/110468657-53e7c200-80b7-11eb-872a-383ff9a1ec61.png)

**Desktop (please complete the following information):**
 - OS: Endless OS
 - Version: 3.9.3

**Comment by LeandroStanger** [comment]
```
Are you sure the translation is complete?
```
Yes https://hosted.weblate.org/projects/bottles/bottles/pt_BR

**Comment by mirkobrombin** [comment]
Strange, except for one string, they are all translatable and the files are generated correctly. Also in po / POTFILES all files are correctly inserted.

I will check the build process as soon as possible.

**Comment by Lvaskz** [comment]
Same here with spanish translation

**Comment by LeandroStanger** [comment]
Any progress?

**Comment by mirkobrombin** [comment]
I haven't had time to watch yet. You can try to figure out the problem yourself by compiling via the `appimage-build.sh` script in the project root.

**Comment by mirkobrombin** [comment]
Should be fixed by 7970107

**Comment by LeandroStanger** [comment]
```
Should be fixed by 7970107
```

It has not been fixed
![Captura de tela de 2021-05-03 19-36-44](https://user-images.githubusercontent.com/26097419/116941881-ea170f00-ac46-11eb-9be2-eee0a0dfe27d.png)

**Comment by mirkobrombin** [comment]
Are you using the latest from flathub?

**Comment by LeandroStanger** [comment]
```
Are you using the latest from flathub beta?
```
Yes

![Captura de tela de 2021-05-04 18-43-11](https://user-images.githubusercontent.com/26097419/117073725-ae447e00-ad08-11eb-9754-93c0a5dc722a.png)

**Comment by mirkobrombin** [comment]
> ```
> Are you using the latest from flathub beta?
> ```
> 
> Yes
> 
> ![Captura de tela de 2021-05-04 18-43-11](https://user-images.githubusercontent.com/26097419/117073725-ae447e00-ad08-11eb-9754-93c0a5dc722a.png)

I have two tests for you to try, the first by starting the flatpak from the terminal passing the language as an environment variable:

```bash
LANG=pt_BR.utf-8 flatpak run com.usebottles.bottles
```

If that doesn't work, can you check if the AppImage has full translations?

**Comment by LeandroStanger** [comment]
```
I have two tests for you to try, the first by starting the flatpak from the terminal passing the language as an environment variable:

LC_ALL="pt_BR.UTF-8" LC_CTYPE="pt_BR.UTF-8" LANG=pt_BR.UTF-8 flatpak run com.usebottles.bottles
```
Doesn't work
![Captura de tela de 2021-05-05 18-33-59](https://user-images.githubusercontent.com/26097419/117212823-368e5600-add1-11eb-8f24-cdd4f3f36341.png)
```
can you check if the AppImage has full translations?
```
![Captura de tela de 2021-05-05 18-35-43](https://user-images.githubusercontent.com/26097419/117212886-4c9c1680-add1-11eb-9309-d662aa7dca3f.png)

**Comment by mirkobrombin** [comment]
Ok this is weird, to me it is working with both packages

**Comment by Lvaskz** [comment]
With snap package translations are not working.

**Comment by mirkobrombin** [comment]
@LeandroStanger @Lvaskz the [latest unstable AppImage](https://github.com/bottlesdevs/Bottles/releases/tag/unstable) build proposes a fix that should fix the problem. Give me feedback please.

**Comment by Lvaskz** [comment]
Any bottles appimage has not this issue with translations in my case. The problem is with flatpak and snap packages

**Comment by Lvaskz** [comment]
With the latest version of snap bottles, the problem remains

**Comment by mirkobrombin** [comment]
> Any bottles appimage has not this issue with translations in my case. The problem is with flatpak and snap packages

The AppImage is the official distribution format of Bottles, I need to know if the latest unstable still works for you before I worry if the update also works for Flatpak.

**Comment by LeandroStanger** [comment]
Update also works for Flatpak

![Captura de tela de 2021-05-23 08-12-01](https://user-images.githubusercontent.com/26097419/119258123-bde41380-bb9e-11eb-939a-b33ed52b1b4e.png)
