### ISSUE TITLE
[Bug]: 'Add to Steam' and 'Add Desktop Entry' do not work for Ubisoft Connect games using the integration.

### ISSUE THREAD

**Issue by ak-42** [bottlesdevs/Bottles#1855]
### Describe the bug

I have a bottle with Ubisoft Connect and a game installed within it, Trackmania 2020. Ubisoft Connect was installed using the installer script from Installers section, and both the Ubisoft Connect and the game were added to the programs list automatically.
Launching both Ubisoft Connect, and the game directly, using the 'play' button in the program list works as expected.

However, if I use 'Add to Steam' functionality on the game's entry, the library entry is correctly created in my steam library, but the game will not launch.
Same goes for 'Add Desktop Entry'. The entry is created, and it shows in KDE menu, but the game will not launch using the newly created entry.
As a workaround, if I add Ubisoft Connect itself using 'Add to Steam' button, it works, but launching directly into the game would be much preferable.

### To Reproduce

1. Install Ubisoft Connect.
2. Install any game (for consistency, try Trackmania, it is free and only a 2 GB download).
3. Try launching the automatically integrated game via Bottles UI. It should work.
4. Select 'Add to Steam' for the game.
5. Try to launch the game via the newly created library entry in Steam. It should not work.

### Package

Flatpak from Flathub

### Distribution

Steam Deck/Holo 3.2 (immutable Arch)

### Health Check

```shell
Version: 2022.7.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 7779737600
    Free: 7779594240
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 11.0GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

I can replicate this issue on Fedora 36 as well.

Terminal outputs (only new lines after pressing 'play' in Steam)

Terminal output from `flatpak run com.usebottles.bottles`:
```
00:16:04 (INFO) Forcing offline mode 
Program Trackmania not found
```

Terminal output from `steam`:
```
GameAction [AppID 3744456160, ActionID 5] : LaunchApp changed task to SynchronizingControllerConfig with ""

(steam:6326): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
GameAction [AppID 3744456160, ActionID 5] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 3744456160, ActionID 5] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 3744456160, ActionID 5] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 3744456160, ActionID 5] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3744456160 -- xdg-open bottles:run/Ubisoft-Connect/'Trackmania'\0
Game process added : AppID 0 "/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3744456160 -- xdg-open bottles:run/Ubisoft-Connect/'Trackmania'", ProcID 8519, IP 0.0.0.0:0
chdir /home/deck/.var/app/com.usebottles.bottles/data/bottles/bottles/Ubisoft-Connect
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 3744456160, ActionID 5] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

(steam:6326): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:6326): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Game process removed: AppID 0 "/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3744456160 -- xdg-open bottles:run/Ubisoft-Connect/'Trackmania'", ProcID 8519 
ThreadGetProcessExitCode: no such process 8531
ThreadGetProcessExitCode: no such process 8524
ThreadGetProcessExitCode: no such process 8521
ThreadGetProcessExitCode: no such process 8520
Uploaded AppInterfaceStats to Steam

(steam:6326): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
```

**Comment by ak-42** [comment]
It may be possible that this issue is not strictly limited to Ubisoft Connect integrations. Since writing this bug report, I've experienced the same issue for other non-Ubisoft Connect games, installed via their normal installers. It's just that I cannot consistently replicate it when running installers directly, and I can replicate it when using Ubisoft Connect.

For standalone games, a workaround is to manually re-add the .exe, and then it normally works.

**Comment by mirkobrombin** [comment]
> It may be possible that this issue is not strictly limited to Ubisoft Connect integrations. Since writing this bug report, I've experienced the same issue for other non-Ubisoft Connect games, installed via their normal installers. It's just that I cannot consistently replicate it when running installers directly, and I can replicate it when using Ubisoft Connect.
> 
> For standalone games, a workaround is to manually re-add the .exe, and then it normally works.

Fixed some commits ago

**Comment by Schroedingers-Cat** [comment]
With Bottles `2022.8.14-brescia`, newly created entries to the steam library that work fine when launched from Bottles are still not starting properly when launched from Steam:  
```
GameAction [AppID 3437804548, ActionID 1] : LaunchApp changed task to SynchronizingControllerConfig with ""

(steam:133877): Gtk-WARNING **: 23:21:49.414: gtk_disable_setlocale() must be called before gtk_init()
GameAction [AppID 3437804548, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 3437804548, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 3437804548, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 3437804548, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3437804548 -- xdg-open bottles:run/Rockstar-Games/'Grand Theft Auto V'\0
Game process added : AppID 0 "/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3437804548 -- xdg-open bottles:run/Rockstar-Games/'Grand Theft Auto V'", ProcID 134292, IP 0.0.0.0:0
chdir /home/deck/.var/app/com.usebottles.bottles/data/bottles/bottles/Rockstar-Games
GameAction [AppID 3437804548, ActionID 1] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

(steam:133877): Gtk-WARNING **: 23:21:49.692: gtk_disable_setlocale() must be called before gtk_init()
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

(steam:133877): Gtk-WARNING **: 23:21:49.751: gtk_disable_setlocale() must be called before gtk_init()
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Game process removed: AppID 0 "/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3437804548 -- xdg-open bottles:run/Rockstar-Games/'Grand Theft Auto V'", ProcID 134292
ThreadGetProcessExitCode: no such process 134305
ThreadGetProcessExitCode: no such process 134298
ThreadGetProcessExitCode: no such process 134294
ThreadGetProcessExitCode: no such process 134293
Uploaded AppInterfaceStats to Steam

(steam:133877): Gtk-WARNING **: 23:21:51.549: gtk_disable_setlocale() must be called before gtk_init()
```
