### ISSUE TITLE
[Bug]: Cannot launch Bottles anymore

### ISSUE THREAD

**Issue by SoftwareRat** [bottlesdevs/Bottles#1908]
### Describe the bug

I cannot launch Bottles anymore, I tried to delete ~/.local/share/flatpak but it didn't worked

### To Reproduce

idk, I just have an Ubisoft Connect bottle and now I cannot launch

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04.1 LTS

### Troubleshooting Logs

```shell
19:40:51 (INFO) Bottles Started! 
19:40:53 (INFO) Catalog components loaded 
19:40:53 (INFO) Catalog installers loaded 
19:40:53 (INFO) Catalog dependencies loaded 
19:40:53 (INFO) Performing Bottles checks… 
19:40:53 (INFO) Dxvks found:
	 - dxvk-1.10.2
 
19:40:53 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.6-1-5b73139
 
19:40:53 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.5.4
 
19:40:53 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.0
 
19:40:53 (INFO) Runners found:
	 - sys-wine-7.0
	 - soda-7.0-2
 
19:40:54 (INFO) Bottles found:
	 - Ubisoft Connect
 
19:40:54 (INFO) Library saved 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/window.py", line 154, in set_manager
    self.page_library = LibraryView(self)
  File "/app/share/bottles/bottles/views/library.py", line 43, in __init__
    self.update()
  File "/app/share/bottles/bottles/views/library.py", line 56, in update
    entry = LibraryEntry(self, u, e)
  File "/app/share/bottles/bottles/widgets/library.py", line 78, in __init__
    path = ThumbnailManager.get_path(self.config, entry['thumbnail'])
  File "/app/share/bottles/bottles/backend/managers/thumbnail.py", line 32, in get_path
    return ThumbnailManager.__load_grid(config, uri)
  File "/app/share/bottles/bottles/backend/managers/thumbnail.py", line 42, in __load_grid
    bottle_path = ManagerUtils.get_bottle_path(config)
  File "/app/share/bottles/bottles/backend/utils/manager.py", line 86, in get_bottle_path
    if config.get("Environment") == "Steam":
AttributeError: 'NoneType' object has no attribute 'get'
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by mirkobrombin** [comment]
Fixed in 2022.7.28-2

**Comment by SoftwareRat** [comment]
I use the version 2022.7.28-brescia-2, so it's not fixed for me

**Comment by SoftwareRat** [comment]
Same logs and GUI is stuck to this:
![image](https://user-images.githubusercontent.com/40393784/183501067-1bf4e2a7-42da-42ab-8929-4ae9096a9dce.png)
