### ISSUE TITLE
Reference existing virtual directory instead of creating anew

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#2263]
Adding the game's .exe to the bottle's program list via the "Add shortcut" button creates a new document mapping resulting in a virtual directory with only that .exe inside. I have to use Wine's explorer to launch the game by navigating to the .exe location and double clicking it (`T:\...\...\abc.exe`). Maybe it should be possible to select the .exe inside the flatpak document map so that it reuses the previous mapping (in my case the one under `/run/user/1000/doc/19ef51/.../.../abc.exe`).
EDIT: Or there could be a button titled "Add internal shortcut" that shows a file picker similar to the Wine's explorer such that it works inside the Wine's world... I don't know... Probably needs some conceptual design work.

_Originally posted by @tesfabpel in https://github.com/bottlesdevs/Bottles/issues/2251#issuecomment-1312809870_

**Comment by koplo199** [comment]
It was an xdg-desktop-portal bug, and it is now resolved as of 1.18.0.

**Comment by gwuen** [comment]
> It was an xdg-desktop-portal bug, and it is now resolved as of 1.18.0.

This still seems to occur with xdg-desktop-portal 1.20.3. When selecting an executable from a directory that already has a drive letter, the exe still gets its own directory in `/run/user/$UID/doc/`.

While this poses some problems for Bottles, are you sure this behavior isn't intended by Flatpak or the Desktop Portal?
