### ISSUE TITLE
[Bug]: First start stuck on Almost done

### ISSUE THREAD

**Issue by janltu** [bottlesdevs/Bottles#2403]
### Describe the bug

I just downloaded bottles on flatpak started it for the first time and its stuck on almost done.

Console log:

[...]
18:19:34 (INFO) Renaming [dxvk-2.0-1-18b0ef6.tar.gz] to [dxvk-2.0-1-18b0ef6.tar.gz]. 
18:19:34 (ERROR) Downloaded file [dxvk-2.0-1-18b0ef6.tar.gz] looks corrupted. 
18:19:34 (ERROR) Source cksum: [f7121c4c7bebc257fbb1626690a7dd06] downloaded: [81d4f690b6cd535eaf642ab4385f62c2] 
18:19:34 (ERROR) Removing corrupted file [dxvk-2.0-1-18b0ef6.tar.gz]. 
18:19:34 (ERROR) Extraction failed! Archive ends earlier than expected. 
18:19:34 (WARNING) No dxvk found. 

happens everytime already tried restarting

### To Reproduce

1. Click on Continue on first start 
2. Be stuck

### Package

Flatpak from Flathub

### Distribution

pop_OS!

### Troubleshooting Logs

```shell
cant click installation has not finished
```

**Comment by ijaure299** [comment]
same, install Pop OS and I have exaclly the same problem

**Comment by ZeitDev** [comment]
steamOS, same error, same log

**Comment by Zardeth** [comment]
Same issue on SteamOS

**Comment by EnfrigFalco** [comment]
Fresh install across a desktop and laptop both Fedora 37 can confirm stuck on "Almost Done" tried both flatpak and repo, both computers. Bottles is definitely bugged

**Comment by bunglesss** [comment]
I'm getting this as well on latest Fedora, it just goes round and round saying runtime.tar.gz is corrupted. Fresh install of Fedora from Live CD with nothing else installed on it but Bottles.

**Comment by Kinsteen** [comment]
Can you all send logs about which file exactly was corrupted please?

**Comment by bunglesss** [comment]
Hi mate, I just tried to get the log off that box, but not winning. Its basically downloading runtime.tar.gz over and over again saying its corrupted and the archive ends too soon, then eventually Bottles blows up and crashes.

**Comment by bunglesss** [comment]
[temp.log.zip](https://github.com/bottlesdevs/Bottles/files/10270830/temp.log.zip)

**Comment by bunglesss** [comment]
Oh, was installed from RPM not Flatpak here by the way.

**Comment by Kinsteen** [comment]
Fedora Bottles is 7 months old, it will not work. I suggest using the Flatpak version or asking the maintainer of the package to update it

**Comment by bunglesss** [comment]
Yeah, works fine on Flatpak, oops, sorry mate!

**Comment by dawnofwar911** [comment]
In my case it's the same "dxvk-2.0-1-18b0ef6.tar.gz" file that failed to be validated checksum wise after the download. Couldn't find that version referenced in the dxvk github either. Hence just needed to skip that install and the rest for the downloads work fine.

**Comment by Kinsteen** [comment]
@dawnofwar911 Hey, normally Bottles should not download this exact dxvk, but dxvk-2.0-1-12901b5. What version are you using? Can you send Bottles logs?

**Comment by fangpenlin** [comment]
I encountered the same issue, but it somehow works after a reboot

**Comment by alaviss** [comment]
Same issue here on NixOS

<details>
<summary>Logs (click to expand)</summary>

```
F: Can't find a11y bus: GDBus.Error:org.a11y.Bus.Error: Failed to spawn child process “/run/current-system/sw/bin/dbus-daemon” (No such file or directory)

(bottles:2): Gtk-WARNING **: 05:56:35.581: Unable to acquire the address of the accessibility bus: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown. If you are attempting to run GTK without a11y support, GTK_A11Y should be set to 'none'.
05:56:36 (INFO) Bottles Started!
05:56:46 (INFO) Catalog components loaded
05:56:47 (INFO) Catalog installers loaded
05:56:49 (INFO) Catalog dependencies loaded
05:56:49 (INFO) Performing Bottles checks…
05:56:49 (INFO) Runners found:
         - sys-wine-7.0.1


(bottles:2): Gtk-CRITICAL **: 05:56:52.824: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed
05:56:53 (INFO) Library saved
05:56:57 (INFO) Performing Bottles checks…
05:56:57 (WARNING) No dxvk found.
05:57:01 (INFO) Installing component: [dxvk-2.0-1-12901b5].
05:57:01 (WARNING) File [dxvk-2.0-1-12901b5.tar.gz] already exists in temp, skipping.
05:57:01 (ERROR) Downloaded file [dxvk-2.0-1-12901b5.tar.gz] looks corrupted.
05:57:01 (ERROR) Source cksum: [5cabe70d766d23439da9aa256d35e463] downloaded: [7cfddacf569612b15560eb818d8ada16]
05:57:01 (ERROR) Removing corrupted file [dxvk-2.0-1-12901b5.tar.gz].
05:57:01 (ERROR) Extraction failed! Archive ends earlier than expected.
05:57:01 (WARNING) No dxvk found.

```

</details>

**Comment by mirkobrombin** [comment]
There are mixed topics here. Anyway, the dxvk checksum was fixed says ago in the repository directly.

**Comment by ben2talk** [comment]
10:42:45 (WARNING) No managed runners found. 
10:42:50 (INFO) No dependencies found! 
10:42:50 (INFO) No installers found! 
10:42:54 (INFO) Performing Bottles checks… 
10:42:54 (WARNING) No dxvk found. 
10:43:00 (WARNING) No vkd3d found. 
10:43:05 (WARNING) No nvapi found. 
10:43:11 (WARNING) No latencyflex found. 
10:43:22 (WARNING) No WineBridge found. 
10:43:22 (INFO) Runners found:
	- sys-wine-8.0.2

So maybe someone got this fixed - I installed flatpak bottles and I'm getting this looped, preventing access to the GUI.
```
GNOME Application Plat… org.gnome.Platform                       44           system
GNOME Application Plat… org.gnome.Platform                       45           system
. 
..
DXVK                    org.winehq.Wine.DLLs.dxvk       2.3      stable-22.08 system
```
It isn't finding the DXVK which is installed...

**Comment by RichardJECooke** [comment]
This is still happening. The GUI is in an endless loop at `Almost Done` and the console shows the below.  My internet is fine. How to fix please?

```sh
flatpak run com.usebottles.bottles
16:55:50 (INFO) Launching with URI: None 
16:55:50 (INFO) [Activate] request received. 
16:55:50 (INFO) Bottles Started! 
16:55:54 (ERROR) Could not get index for components repository 
16:55:54 (ERROR) Could not get index for installers repository 
16:55:54 (INFO) Performing Bottles checks… 
16:55:54 (INFO) Runners found:
	 - sys-wine-9.0
 
16:55:54 (INFO) No installers found! 
16:55:55 (INFO) Catalog dependencies loaded 
16:56:02 (INFO) Performing Bottles checks… 
16:56:02 (WARNING) No dxvk found. 
16:56:03 (WARNING) No vkd3d found. 
16:56:03 (WARNING) No nvapi found. 
16:56:04 (WARNING) No latencyflex found. 
16:56:05 (WARNING) No WineBridge found. 
16:56:05 (INFO) Runners found:
	 - sys-wine-9.0
 
16:56:05 (WARNING) No managed runners found. 
16:56:06 (INFO) No installers found! 
```

**Comment by RichardJECooke** [comment]
Ah, looks like my problem is a new problem with the same symptom - https://github.com/bottlesdevs/Bottles/issues/3761
