### ISSUE TITLE
[Bug]: Translation not fully applied since the latest release

### ISSUE THREAD

**Issue by AsciiWolf** [bottlesdevs/Bottles#3705]
### Describe the bug

Latest Bottles 51.18 from Flathub. Many strings are now displayed in English on Czech localization of Bottles even though they seem to be fully translated [on Weblate](https://hosted.weblate.org/projects/bottles/bottles/cs/). This was not a problem with previous (51.17) build.

![screenshot](https://github.com/user-attachments/assets/ef06b12c-f9ad-4900-98bb-a9b056429009)

### To Reproduce

1. Use latest Flathub version of Bottles on a system with non-English locale.
2. See how much of the actual app UI is displayed as translated.
3. Compare it [with Weblate](https://hosted.weblate.org/projects/bottles/bottles/).

### Package

Flatpak from Flathub

### Distribution

Fedora 41

### Debugging Information

```shell
Official Package: true
Version: '51.18'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.12.9-200.fc41.x86_64
Disk:
    Total: 16782180352
    Free: 16782008320
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 27.1GiB
Bottles_envs: null
```

**Comment by TheEvilSkeleton** [comment]
Right, this is caused by https://github.com/bottlesdevs/Bottles/commit/2ad91646fbf2ac64882680506b8d4fcb5f91ad52. I won't lie, I completely forgot about translation when I pushed the release. I think this is a good opportunity to follow a similar release pattern to GNOME, where we can implement a string freeze and wait for translators.

**Comment by AsciiWolf** [comment]
Still the same problem with latest Bottles (51.21) in Czech language (that is 100% translated on Weblate).

**Comment by AsciiWolf** [comment]
Still the same problem in latest 51.24.

@TheEvilSkeleton Please re-open. Thanks!
