### ISSUE TITLE
[Bug]: Missing Essential components

### ISSUE THREAD

**Issue by GurkeeratChhina** [bottlesdevs/Bottles#4052]
### Describe the bug

Installing bottles via flatpak and it is missing vkd3d as well as nvapi. Attemption to install via bottles preferences menus gives a 404 error when fetching the tar.gz

### To Reproduce

1. Install bottles `flatpak install flathub com.usebottles.bottles`
2. Run bottles `flatpak run com.usebottles.bottles`
3. Go to bottles preferences > DLL Components and try to install vkd3d or nvapi.
4. Get an error: `(WARNING) Failed to download [https://github.com/bottlesdevs/components/releases/download/vkd3d-proton-2.14.1/vkd3d-proton-2.14.1.tar.gz] with code: 404 != 200 `

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.24'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-580-76-05/lib/nvidia/wine
        amd: &amp;id001
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.16.1-arch1-1
Disk:
    Total: 16372252672
    Free: 16372068352
RAM:
    MemTotal: 30.5GiB
    MemAvailable: 24.9GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
21:16:59 (INFO) Installing component: [dxvk-nvapi-v0.9.0]. 
21:16:59 (WARNING) Failed to download [https://github.com/bottlesdevs/components/releases/download/dxvk-nvapi-v0.9.0/dxvk-nvapi-v0.9.0.tar.gz] with code: 404 != 200 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/component.py", line 98, in async_func
    return self.update_progress(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/bottles/bottles/frontend/widgets/component.py", line 150, in update_progress
    percent = int(received_size * 100 / total_size)
                  ~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for *: 'type' and 'int'
21:16:59 (ERROR) Component installation failed
```

**Comment by LBarrys** [comment]
Same problem here

**Comment by appleGun22** [comment]
Bottles tries to download files that don't even exist...
(`vkd3d-proton-2.14.1.tar.gz` is just one of them)

Going to stick with pure wine for the meantime.

**Comment by trashcatt** [comment]
Same problem here. When trying to install vkd3d and dxvk-nvapi, both links 404.

**Comment by dmwest** [comment]
I'm having the same problem. I can install vk3d-proton-2.13 but vk3d-proton-2.14 and vk3d-proton-2.14.1 fail to download

**Comment by equillar** [comment]
The file it's supposed to download, it dosnt exist anymore. Either the link is broken or down

**Comment by raynix** [comment]
Looks like the file extension changed from .tar.gz to .tar.zst. Should be an easy fix?

https://github.com/HansKristian-Work/vkd3d-proton/releases/download/v2.14.1/vkd3d-proton-2.14.1.tar.zst

Just in case, I noted down steps I used to [install vkd3d and dxvk-nvapi manually](https://raynix.info/archives/4956).

**Comment by KayLilac** [comment]
same thing here, it just outright refuses to download many essential components which is funny because not even a week ago everything everything was working fine.

**Comment by v15as** [comment]
> Looks like the file extension changed from .tar.gz to .tar.zst. Should be an easy fix?
> 
> https://github.com/HansKristian-Work/vkd3d-proton/releases/download/v2.14.1/vkd3d-proton-2.14.1.tar.zst
> 
> Just in case, I noted down steps I used to [install vkd3d and dxvk-nvapi manually](https://raynix.info/archives/4956).

I installed bottles with yay and was getting an error while creating application bottles (gaming bottles were working for some reason) so i uninstalled completely and installed with flatpak. The link that you gave resolves the problem of the missing vkd3d. Thanks!

**Comment by mirkobrombin** [comment]
Fixed in the deps repo

**Comment by ninstar** [comment]
It still appears to be an issue for DXVK-NVAPI?

<img width="981" height="1012" alt="Image" src="https://github.com/user-attachments/assets/c4ac682d-c368-4155-bb61-8a58e2dfcc67" />

I'm using the official Flatpak install.

EDIT: According to this comment https://github.com/bottlesdevs/components/issues/466#issuecomment-3693691300, anything newer than version 6.3.0 seems to be missing from the components repository, I can still install 0.6.4, 0.7.0 and 0.7.1 inside Bottles without an issue (although the terminal output doesn't show where they are being downloaded from). Only versions 0.8.0 and 0.9.0 seem to have broken links.

**Comment by lhw** [comment]
Can confirm. Anything newer than 0.7.1 was deleted from the components repos releases. But you can relatively easily download a release from https://github.com/jp7677/dxvk-nvapi/releases/tag/v0.9.0 and e.g. for flatpak create a dxvk-nvapi-v0.9.0 directory with the contents under `~/.var/app/com.usebottles.bottles/data/bottles/nvapi`.
