### ISSUE TITLE
[BUG] Wine can't open windows on wayland

### ISSUE THREAD

**Issue by Voleil** [bottlesdevs/Bottles#794]
**Describe the bug**
Wine can't open any windows on wayland. Works fine on Xorg. Similar bug to #623 

**Installation**
 - Method: Flatpak
 - Version 2021.12.14-treviso-2

**To Reproduce**
1. Try to open anything in a bottle in wayland
2. See error in terminal
3. No windows show up

**Expected behavior**
Wine windows should open in wayland

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue
 - Version 35
 - Display server: Wayland
**Additional context**
Logs: 
https://gist.github.com/Voleil/94f7dcbf7b2cac9b9ed8bd063389614c

**Comment by mirkobrombin** [comment]
Time to fix wayland support again 👀

**Comment by mirkobrombin** [comment]
Fixed by https://github.com/bottlesdevs/Bottles/commit/228d3f4ea0ded8306c5151328084f83891a3b508

**Comment by Voleil** [comment]
Thanks for the quick update, just tried the new version and it's still not fixed weirdly enough
Logs: https://gist.github.com/Voleil/748d11e214b2d3ca8c940eaf22a3d4c8
Let me know if I can do anything else to help you debug this 👍

**Comment by mirkobrombin** [comment]
> Thanks for the quick update, just tried the new version and it's still not fixed weirdly enough Logs: https://gist.github.com/Voleil/748d11e214b2d3ca8c940eaf22a3d4c8 Let me know if I can do anything else to help you debug this +1

The flatpak build was missing a dependency, we have launched another update, sorry about this
